services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: statsdbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: [ "CMD", "pg_isready", "-U statsdbuser", "-d stats_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-server:
    build:
      context: ./stats-service/stats-server
      dockerfile: Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
      SPRING_DATASOURCE_USERNAME: statsdbuser
      SPRING_DATASOURCE_PASSWORD: 12345

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5436"
    environment:
      POSTGRES_DB: ewm_db
      POSTGRES_USER: ewmdbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm-service:
    build:
      context: ./main-app-service
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm_db
      SPRING_DATASOURCE_USERNAME: ewmdbuser
      SPRING_DATASOURCE_PASSWORD: 12345

